POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
"username":"Tim",
"password":"1234"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
"username":"tung",
"password":"tung"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2RhNDgzNmJkODZhMDlkYzk0M2RmNTQiLCJpYXQiOjE2NzUyNDk3MTh9.8CkXMyrBSlXm3QmFvHqh1jOrBKbFNzL6hPUbb1R_dDU

{
"title":"The beautiful girl",
"description":"Fashion Young Handsome Man in Casual Watch",
"url":"goole.com",
"category":"Travel",
"image":"https://new.axilthemes.com/demo/react/blogar/images/posts/lifestyle-post-03.webp?imwidth=1920"
}

###

GET http://localhost:5000/api/posts/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2I5MzljZWUyNmViN2M0OThhNjA4OGEiLCJpYXQiOjE2NzYzNDQ5NzZ9.iY5VxB3S-XNWmykyWm9PKbd1nrAB1xyxpp7jkIUsEUw

###

PUT http://localhost:5000/api/posts/63da484abd86a09dc943df56
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2RhNDgzNmJkODZhMDlkYzk0M2RmNTQiLCJpYXQiOjE2NzUyNDk3MTh9.8CkXMyrBSlXm3QmFvHqh1jOrBKbFNzL6hPUbb1R_dDU

{
"title":"edit post",
"description":"edit third description",
"url":"dantri.com",
"status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/63da484abd86a09dc943df56
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2RhNDgzNmJkODZhMDlkYzk0M2RmNTQiLCJpYXQiOjE2NzUyNDk3MTh9.8CkXMyrBSlXm3QmFvHqh1jOrBKbFNzL6hPUbb1R_dDU

